# Generated by Django 3.2.16 on 2023-01-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Content',
            new_name='content',
        ),
    ]
